/*
 * THIS FILE IS AUTOMATICALLY GENERATED AND DO NOT EDIT IT MANUALLY!
 *
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sht4x.h"
#include "sensirion_i2c_hal.h"
#include "sensirion_common.h"

static uint8_t _i2c_address;

static float _convert_ticks_to_celsius(uint16_t ticks) {
    return (float)ticks * 175.0f / 65535.0f - 45.0f;
}

static float _convert_ticks_to_rh(uint16_t ticks) {
    return (float)ticks * 125.0f / 65535.0f - 6.0f;
}

int16_t sht4x_measure_high_precision(int32_t* temperature, int32_t* humidity) {
    uint8_t command = 0xFD;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(10000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_measure_medium_precision(int32_t* temperature,
                                       int32_t* humidity) {
    uint8_t command = 0xF6;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(5000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_measure_lowest_precision(int32_t* temperature,
                                       int32_t* humidity) {
    uint8_t command = 0xE0;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(2000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_activate_highest_heater_power_long(int32_t* temperature,
                                                 int32_t* humidity) {
    uint8_t command = 0x39;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(1100000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_activate_highest_heater_power_short(int32_t* temperature,
                                                  int32_t* humidity) {
    uint8_t command = 0x32;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(110000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_activate_medium_heater_power_long(int32_t* temperature,
                                                int32_t* humidity) {
    uint8_t command = 0x2F;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(1100000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_activate_medium_heater_power_short(int32_t* temperature,
                                                 int32_t* humidity) {
    uint8_t command = 0x24;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(110000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_activate_lowest_heater_power_long(int32_t* temperature,
                                                int32_t* humidity) {
    uint8_t command = 0x1E;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(1100000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_activate_lowest_heater_power_short(int32_t* temperature,
                                                 int32_t* humidity) {
    uint8_t command = 0x15;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(110000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    uint16_t temperature_ticks = sensirion_common_bytes_to_uint16_t(&buffer[0]);
    uint16_t humidity_ticks = sensirion_common_bytes_to_uint16_t(&buffer[3]);

    *temperature = (17500 * temperature_ticks / 65535) - 4500;
    *humidity = (12500 * humidity_ticks / 65535) - 600;

    return 0;
}

int16_t sht4x_serial_number(uint32_t* serial_number) {
    uint8_t command = 0x89;
    uint8_t buffer[6];
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(10000);
    error = sensirion_i2c_hal_read(_i2c_address, buffer, 6);
    if (error) {
        return error;
    }
    *serial_number = sensirion_common_bytes_to_uint32_t(&buffer[0]);
    return 0;
}

int16_t sht4x_soft_reset() {
    uint8_t command = 0x94;
    int16_t error = sensirion_i2c_hal_write(_i2c_address, &command, 1);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_us(2000);
    return 0;
}

int16_t sht4x_probe() {
    uint32_t serial;
    return sht4x_serial_number(&serial);
}

int16_t sht4x_measure_blocking_read(float* temperature, float* humidity) {
    int32_t temp_milli;
    int32_t hum_milli;
    int16_t error = sht4x_measure_high_precision(&temp_milli, &hum_milli);
    if (error) {
        return error;
    }
    *temperature = (float)temp_milli / 100.0f;
    *humidity = (float)hum_milli / 100.0f;
    return 0;
}

int16_t sht4x_measure_blocking_read_raw(int32_t* temperature, uint32_t* humidity) {
    int32_t temp_milli;
    int32_t hum_milli;
    int16_t error = sht4x_measure_high_precision(&temp_milli, &hum_milli);
    if (error) {
        return error;
    }
    *temperature = temp_milli;
    *humidity = (uint32_t)hum_milli;
    return 0;
}
int16_t sht4x_init(uint8_t i2c_address) {
    _i2c_address = i2c_address;
    return sht4x_soft_reset();
}
