/*
 * THIS FILE IS AUTOMATICALLY GENERATED AND DO NOT EDIT IT MANUALLY!
 *
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SHT4X_H
#define SHT4X_H

#include "sensirion_config.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * SHT4X_I2C_ADDR_44 - I2C address for SHT4X
 */
#define SHT4X_I2C_ADDR_44 0x44
/**
 * SHT4X_I2C_ADDR_45 - I2C address for SHT4X
 */
#define SHT4X_I2C_ADDR_45 0x45

/**
 * sht4x_measure_high_precision() - Measure temperature and relative humidity
 * with high precision.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_measure_high_precision(int32_t* temperature, int32_t* humidity);

/**
 * sht4x_measure_medium_precision() - Measure temperature and relative humidity
 * with medium precision.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_measure_medium_precision(int32_t* temperature,
                                       int32_t* humidity);

/**
 * sht4x_measure_lowest_precision() - Measure temperature and relative humidity
 * with lowest precision.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_measure_lowest_precision(int32_t* temperature,
                                       int32_t* humidity);

/**
 * sht4x_activate_highest_heater_power_long() - Activate heater with highest
 * power for 1s.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_activate_highest_heater_power_long(int32_t* temperature,
                                                 int32_t* humidity);

/**
 * sht4x_activate_highest_heater_power_short() - Activate heater with highest
 * power for 0.1s.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_activate_highest_heater_power_short(int32_t* temperature,
                                                  int32_t* humidity);

/**
 * sht4x_activate_medium_heater_power_long() - Activate heater with medium
 * power for 1s.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_activate_medium_heater_power_long(int32_t* temperature,
                                                int32_t* humidity);

/**
 * sht4x_activate_medium_heater_power_short() - Activate heater with medium
 * power for 0.1s.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_activate_medium_heater_power_short(int32_t* temperature,
                                                 int32_t* humidity);

/**
 * sht4x_activate_lowest_heater_power_long() - Activate heater with lowest
 * power for 1s.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_activate_lowest_heater_power_long(int32_t* temperature,
                                                int32_t* humidity);

/**
 * sht4x_activate_lowest_heater_power_short() - Activate heater with lowest
 * power for 0.1s.
 *
 * @temperature: Temperature in milli degrees centigrade.
 * @humidity: Relative humidity in milli percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_activate_lowest_heater_power_short(int32_t* temperature,
                                                 int32_t* humidity);

/**
 * sht4x_serial_number() - Read the serial number.
 *
 * @serial_number: Unique serial number.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_serial_number(uint32_t* serial_number);

/**
 * sht4x_soft_reset() - Perform a soft reset.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_soft_reset(void);

/**
 * sht4x_probe() - Probe for the sensor.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_probe(void);

/**
 * sht4x_measure_blocking_read() - Measure temperature and relative humidity
 * and block until the measurement is finished.
 *
 * @temperature: Temperature in degrees celsius.
 * @humidity: Relative humidity in percent.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_measure_blocking_read(float* temperature, float* humidity);

//leowang 260118
int16_t sht4x_measure_blocking_read_raw(int32_t* temperature, uint32_t* humidity);
/**
 * sht4x_init() - Initializes the SHT4x sensor.
 * @i2c_address: The I2C address to be used for the sensor.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sht4x_init(uint8_t i2c_address);

#ifdef __cplusplus
}
#endif

#endif /* SHT4X_H */
